[package]
name = "ide-assists"
version = "0.0.0"
repository.workspace = true
description = "Code assists for rust-analyzer."

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
cov-mark = "2.0.0"

itertools.workspace = true
either.workspace = true
smallvec.workspace = true
tracing = { workspace = true, features = ["attributes"] }

# local deps
stdx.workspace = true
syntax.workspace = true
ide-db.workspace = true
hir.workspace = true

# verusfmt = { git = "https://github.com/verus-lang/verusfmt.git", branch = "optional-updater", default-features = false }
verusfmt = { version = "0.7.0", default-features = false }
tempfile = "3.10.1"
test-fixture.workspace = true

[dev-dependencies]
expect-test = "1.5.1"

# local deps
test-utils.workspace = true
test-fixture.workspace = true

[features]
in-rust-tree = []
proof-action = []

[lints]
workspace = true
